package com.servicecode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-09T21:41:21.515+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://www.WebService.demo.example.com", name = "CommonService")
@XmlSeeAlso({ObjectFactory.class})
public interface CommonService {

    @WebMethod
    @RequestWrapper(localName = "getQueryData", targetNamespace = "http://www.WebService.demo.example.com", className = "com.servicecode.GetQueryData")
    @ResponseWrapper(localName = "getQueryDataResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.servicecode.GetQueryDataResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String getQueryData(
        @WebParam(name = "QueryName", targetNamespace = "")
        java.lang.String queryName
    );
}
